version: "3"
services:
  broker-1:
    image: "rocketmq-on-s3:arm64-0.0.1"
    # https://docs.docker.com/compose/compose-file/05-services/#entrypoint
    ports:
      - "8081:8081"
    # https://docs.docker.com/compose/compose-file/05-services/#depends_on
    depends_on:
      mysql-server:
        condition: service_healthy
        restart: true
  tool:
    image: "ubuntu:22.04"
    command: ["sleep","infinity"]
  mysql-server:
    image: "mysql:8.1"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - "./ddl.sql:/docker-entrypoint-initdb.d/1.sql"
    # https://docs.docker.com/compose/startup-order/
    # https://docs.docker.com/compose/compose-file/05-services/#healthcheck
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10