version: "3"
services:
  broker-1:
    image: "rocketmq-on-s3:0.0.1"
    # https://docs.docker.com/compose/compose-file/05-services/#entrypoint
    environment:
      - ROCKETMQ_NODE_NAME=broker-1
      - ROCKETMQ_NODE_BIND_ADDRESS=0.0.0.0:8081
      - ROCKETMQ_NODE_ADVERTISE_ADDRESS=10.1.0.110:8081
    ports:
      - "8081:8081"
    # https://docs.docker.com/compose/compose-file/05-services/#depends_on
    depends_on:
      mysql-server:
        condition: service_healthy
  broker-2:
    image: "rocketmq-on-s3:0.0.1"
    # https://docs.docker.com/compose/compose-file/05-services/#entrypoint
    environment:
      - ROCKETMQ_NODE_NAME=broker-2
      - ROCKETMQ_NODE_BIND_ADDRESS=0.0.0.0:8181
      - ROCKETMQ_NODE_ADVERTISE_ADDRESS=10.1.0.110:8181
    ports:
      - "8181:8181"
    # https://docs.docker.com/compose/compose-file/05-services/#depends_on
    depends_on:
      mysql-server:
        condition: service_healthy
  mysql-server:
    image: "mysql:8.1"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=metadata
    ports:
      - "3306:3306"
    volumes:
      - "./ddl.sql:/docker-entrypoint-initdb.d/1.sql"
    # https://docs.docker.com/compose/startup-order/
    # https://docs.docker.com/compose/compose-file/05-services/#healthcheck
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10