version: "3"
services:
  broker-1:
    image: "rocketmq-on-s3:arm64-0.0.1"
    # https://docs.docker.com/compose/compose-file/05-services/#entrypoint
    environment:
      - ROCKETMQ_NODE_NAME=broker-1
      - ROCKETMQ_NODE_BIND_ADDRESS=0.0.0.0:8081
      - ROCKETMQ_NODE_ADVERTISE_ADDRESS=192.168.123.147:8081
    ports:
      - "8081:8081"
    # https://docs.docker.com/compose/compose-file/05-services/#depends_on
    depends_on:
      mysql-server:
        condition: service_healthy
        restart: true
  broker-2:
    image: "rocketmq-on-s3:arm64-0.0.1"
    # https://docs.docker.com/compose/compose-file/05-services/#entrypoint
    environment:
      - ROCKETMQ_NODE_NAME=broker-2
      - ROCKETMQ_NODE_BIND_ADDRESS=0.0.0.0:8181
      - ROCKETMQ_NODE_ADVERTISE_ADDRESS=192.168.123.147:8181
    ports:
      - "8181:8181"
    # https://docs.docker.com/compose/compose-file/05-services/#depends_on
    depends_on:
      mysql-server:
        condition: service_healthy
        restart: true
  mysql-server:
    image: "mysql:8.1"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./ddl.sql:/docker-entrypoint-initdb.d/2.sql"
    # https://docs.docker.com/compose/startup-order/
    # https://docs.docker.com/compose/compose-file/05-services/#healthcheck
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10