# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for rocketmq-k8s-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

broker:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
    repository: "automqinc/automq-for-rocketmq"
    tag: "v0.0.2-alpha"

  persistence:
    enabled: false
    size: 8Gi

  nameOverride: "broker"
  fullnameOverride: ""

  conf:
    name: ""
    clusterNameOverride: ""
    brokerNamePrefixOverride: ""

    inner:
      accessKey: "automq"
      secretKey: "rocketmq"

    s3Stream:
      s3WALPath: "/tmp/s3rocketmq/wal"
      s3Endpoint: "http://minio.local:9000"
      s3Bucket: "bucket-name"
      s3Region: "us-east-1"
      s3ForcePathStyle: true
      s3AccessKey: "access-key"
      s3SecretKey: "secret-key"
      networkBaselineBandwidth: 5242880
      refillPeriodMs: 100
    db:
      url: "jdbc:mysql://mysql-server:3306/metadata"
      userName: "root"
      password: "password"
    store:
      kvPath: "/tmp/s3rocketmq/kvstore"
    controller:
      recycleS3IntervalInSecs: 360
      dumpHeapOnError: true
    metrics:
      exporterType: "OTLP_GRPC"
      grpcExporterTarget: "http://10.129.63.127:4317"
      grpcExporterHeader: ""
      grpcExporterTimeOutInMills: 31000
      periodicExporterIntervalInMills: 30000
      promExporterPort: 5557
      promExporterHost: "localhost"
      labels: ""
      exportInDelta: false

  service:
    port: 8081

  jvmMemory: " -Xms4g -Xmx4g -Xmn2g -XX:MaxDirectMemorySize=8g "
  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 4
      memory: 8Gi

  nodeSelector: { }

  tolerations: [ ]

