# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

broker:
  replicaCount: 1
  conf:
    clusterNameOverride: "automq"
    s3Stream:
      s3WALPath: "/tmp/s3rocketmq/wal"
      s3Endpoint: "http://s3-localstack:4566"
      s3Bucket: "ros"
      s3Region: "eu-west-2"
      s3ForcePathStyle: true
      s3AccessKey: "foot"
      s3SecretKey: "bar"
      networkBaselineBandwidth: 5242880
      refillPeriodMs: 100

    store:
      kvPath: "/tmp/s3rocketmq/kvstore"
    db:
      url: "jdbc:mysql://mysql:3306/metadata"
      userName: "root"
      password: "passward"
    controller:
      recycleS3IntervalInSecs: 360
      dumpHeapOnError: true
    metrics:
      exporterType: "OTLP_GRPC"
      grpcExporterTarget: "http://10.129.63.127:4317"
      grpcExporterHeader: ""
      grpcExporterTimeOutInMills: 31000
      periodicExporterIntervalInMills: 30000
      promExporterPort: 5557
      promExporterHost: "localhost"
      labels: ""
      exportInDelta: false
