
enableStartupScripts: true

service:
  type: LoadBalancer

startupScriptContent: |
    #!/bin/bash
    set -e
    export TERM=ansi
    export AWS_ACCESS_KEY_ID=foot
    export AWS_SECRET_ACCESS_KEY=bar
    export AWS_DEFAULT_REGION=eu-west-2
    export AWS_DEFAULT_BUCKETS=ros
    export AWS_S3_ENDPOINT=http://localhost:4566
    export PAGER=

    echo "S3 Configuration started"

    aws --endpoint-url=$AWS_S3_ENDPOINT s3 mb s3://$AWS_DEFAULT_BUCKETS
    aws --endpoint-url=$AWS_S3_ENDPOINT s3 cp /tmp/localstack/test-data/ s3://$AWS_DEFAULT_BUCKETS/chart --recursive

    echo "S3 Configured"