/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.automq.rocketmq.common.model;

import com.automq.rocketmq.common.model.generated.FlatMessage;
import java.util.Optional;

/**
 * A wrapper around a FlatMessage with additional metadata.
 * <p>
 * Typically used to wrap a message that is being consumed from a queue.
 */
public class FlatMessageExt {
    // The raw message as retrieved from the storage layer.
    private FlatMessage message;

    // The receiptHandle generated by the receive operation that retrieved this message.
    private String receiptHandle;

    // The offset of the message in the queue
    private long offset = -1;

    private FlatMessageExt() {
    }

    public static class Builder {
        private final FlatMessageExt messageExt;

        private Builder() {
            messageExt = new FlatMessageExt();
        }

        public static Builder builder() {
            return new Builder();
        }

        public Builder message(FlatMessage message) {
            messageExt.message = message;
            return this;
        }

        public Builder receiptHandle(String receiptHandle) {
            messageExt.receiptHandle = receiptHandle;
            return this;
        }

        public Builder offset(long offset) {
            messageExt.offset = offset;
            return this;
        }

        public FlatMessageExt build() {
            if (messageExt.message == null) {
                throw new IllegalArgumentException("Message not set");
            }
            if (messageExt.offset < 0) {
                throw new IllegalArgumentException("Message offset not set or invalid");
            }
            return messageExt;
        }
    }

    public FlatMessage message() {
        return message;
    }

    public Optional<String> receiptHandle() {
        return Optional.ofNullable(receiptHandle);
    }

    public long offset() {
        return offset;
    }

    public int reconsumeCount() {
        return message.systemProperties().deliveryAttempt();
    }

    public void setReconsumeCount(int reconsumeCount) {
        message.systemProperties().mutateDeliveryAttempt(reconsumeCount);
    }
}
