/*
 * Copyright 2024, AutoMQ CO.,LTD.
 *
 * Use of this software is governed by the Business Source License
 * included in the file BSL.md
 *
 * As of the Change Date specified in that file, in accordance with
 * the Business Source License, use of this software will be governed
 * by the Apache License, Version 2.0
 */

package com.automq.rocketmq.common.model;

import com.automq.rocketmq.common.model.generated.FlatMessage;
import com.automq.rocketmq.common.system.MessageConstants;
import java.util.Optional;

/**
 * A wrapper around a FlatMessage with additional metadata.
 * <p>
 * Typically used to wrap a message that is being consumed from a queue.
 */
public class FlatMessageExt {
    // The raw message as retrieved from the storage layer.
    private FlatMessage message;

    // The receiptHandle generated by the pop operation that retrieved this message.
    private String receiptHandle;

    // The offset of the message in the queue
    private long offset = MessageConstants.UNINITIALIZED_OFFSET;

    private FlatMessageExt() {
    }

    public static class Builder {
        private final FlatMessageExt messageExt;

        private Builder() {
            messageExt = new FlatMessageExt();
        }

        public static Builder builder() {
            return new Builder();
        }

        public Builder message(FlatMessage message) {
            messageExt.message = message;
            return this;
        }

        public Builder receiptHandle(String receiptHandle) {
            messageExt.receiptHandle = receiptHandle;
            return this;
        }

        public Builder offset(long offset) {
            messageExt.offset = offset;
            return this;
        }

        public FlatMessageExt build() {
            if (messageExt.message == null) {
                throw new IllegalArgumentException("Message not set");
            }
            if (messageExt.offset < 0) {
                throw new IllegalArgumentException("Message offset not set or invalid");
            }
            return messageExt;
        }
    }

    public FlatMessage message() {
        return message;
    }

    public Optional<String> receiptHandle() {
        return Optional.ofNullable(receiptHandle);
    }

    public long offset() {
        return offset;
    }

    /**
     * The original offset of the message in the queue.
     * <p>
     * For retry messages, this is the offset of the original message.
     *
     * @return the original offset of the message in the queue
     */
    public long originalOffset() {
        if (isRetryMessage()) {
            return message.systemProperties().originalQueueOffset();
        }
        return offset;
    }

    public int deliveryAttempts() {
        return message.systemProperties().deliveryAttempts();
    }

    public void setDeliveryAttempts(int deliveryAttempts) {
        message.systemProperties().mutateDeliveryAttempts(deliveryAttempts);
    }

    public boolean isRetryMessage() {
        return message.systemProperties().deliveryAttempts() > 1;
    }

    public void setReceiptHandle(String receiptHandle) {
        this.receiptHandle = receiptHandle;
    }

    public void setOriginalQueueOffset(long offset) {
        message.systemProperties().mutateOriginalQueueOffset(offset);
    }

    public long originalQueueOffset() {
        return message.systemProperties().originalQueueOffset();
    }
}
