name: Build with Maven

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  dist-tar:
    name: Build distribution tar
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install flatc
        run: sudo bash install_flatc.sh
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.3.6
        with:
          key: docker-${{ runner.os }}
      - name: Build with Maven
        working-directory: s3stream
        run: mvn clean install -U
