name: Build with Maven

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  dist-tar:
    name: Build with Maven 
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install flatc
        run: sudo apt install -y flatbuffers-compiler
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - name: Build with Maven
        run: mvn clean install
